version: '3.6'

services:
  db:
      image: mysql:latest
      ports:
        - '32000:3306'
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - dbpractice:/var/lib/mysql
volumes:
  dbpractice:
